"""fix issue user relations

Revision ID: 8fc84c78b3e4
Revises: fab149391aa5
Create Date: 2026-01-02 16:54:46.913314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc84c78b3e4'
down_revision: Union[str, Sequence[str], None] = 'fab149391aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('issues_created_by_fkey'), 'issues', type_='foreignkey')
    op.drop_constraint(op.f('issues_assigned_to_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to_id'], ['id'])
    op.drop_column('issues', 'assigned_to')
    op.drop_column('issues', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('issues', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_assigned_to_fkey'), 'issues', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('issues_created_by_fkey'), 'issues', 'users', ['created_by'], ['id'])
    op.drop_column('issues', 'assigned_to_id')
    op.drop_column('issues', 'created_by_id')
    # ### end Alembic commands ###
